nameOverride: ""
fullnameOverride: ""

config:
  postgresDb: kfirs_app
  postgresUser: kfirs_user
  postgresPort: "5432"
  appUsername: kfire312
  sessionCookieSecure: "false"

secrets:
  # If false: create the Secret yourself and set secrets.name to it.
  # If true: this chart creates the Secret using the values below.
  create: false
  name: kfirs-app-secrets

  postgresPassword: "postgres_password"
  appPasswordHash: "scrypt:32768:8:1$PJEaspYClxXbiyY6$b542cb3bbf4f4b1c397e2f938fe2974bab83bbd6e551a2c18df5080d7d77fef444b48f3773f13ac45fcec8e101ad9993ed182472b57bc9ac0d1b58556f95d16a"
  flaskSecretKey: "THIS_IS_MY_LONG_RANDOM_STRING"

postgres:
  image: postgres:16
  storage:
    size: 1Gi

app:
  replicas: 1
  image: kfire312/kfirs-app:v2
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /
  pathType: Prefix

