apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kfirs-app.configName" . }}
  labels:
    {{- include "kfirs-app.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ include "kfirs-app.dbServiceName" . | quote }}
  POSTGRES_PORT: {{ .Values.config.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  APP_USERNAME: {{ .Values.config.appUsername | quote }}
  SESSION_COOKIE_SECURE: {{ .Values.config.sessionCookieSecure | quote }}

