apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfirs-app.dbServiceName" . }}
  labels:
    {{- include "kfirs-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kfirs-app.selectorLabels" . | nindent 4 }}
    component: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

